### ISSUE TITLE
No signature of method: sshDeploy.call()

### ISSUE THREAD

**Issue by ajitsahu** [nrayapati/ssh-deploy-library#3]
Getting below error while running, please have a look
hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: sshDeploy.call() is applicable for argument types: (java.lang.String) values: [dev/deploy.yml]

**Comment by nrayapati** [comment]
Looks like you are sending a list instead of string, sshDeploy var takes string. Can you list the Jenkinsfile here?

**Comment by ajitsahu** [comment]
Sure, I'm using the same Jenkinsfile mentioned in the url [https://jenkins.io/blog/2019/02/06/ssh-steps-for-jenkins-pipeline/#about-the-author](url)
`@Library('ssh_deploy') _

node {
  checkout scm
  sshDeploy('dev/deploy.yml');
}`
Please have a look not sure what exactly I'm missing here or I have added the same deploy.yml file in the same ssh-deploy-library repo.

**Comment by nrayapati** [comment]
Try adding boolean param too, there is dryRun param added recently as well. 

```groovy
@Library('ssh_deploy') _

node {
    checkout scm
    sshDeploy('dev/deploy.yml', false);
}
```

**Comment by ajitsahu** [comment]
Now I'm getting a different error
`groovy.lang.MissingPropertyException: No such property: yaml for class: sshDeploy`

**Comment by nrayapati** [comment]
Try again, I just updated sshDeploy.groovy file, but just for the info, this repo is a reference, consider it as an example, not a full copy of what we have. I would strongly encourage you to clone and troubleshoot all of these minor things. Thank you.

**Comment by ajitsahu** [comment]
Thanks a lot for the suggestions.

**Comment by nrayapati** [comment]
Hope it is working this time.

**Comment by ajitsahu** [comment]
Still investigating the issue, hope this time it will work. Thanks!

**Comment by ajitsahu** [comment]
Got another issue
`java.lang.NullPointerException: Cannot get property 'r_group_1' on null object`

**Comment by ajitsahu** [comment]
here is my yaml file
```
config:
  credentials_id: user_id

remote_groups:
  r_group_1:
    - name: node01
      host: hostname

command_groups:
  c_group_1:
    - commands:
        - 'ls -lrt'
        - 'whoami'
steps:
  deploy:
    - remote_groups:
        - r_group_1
      command_groups:
        - c_group_1
```
